roles:
- src: jborean93.win_openssh
  version: v0.3.0

collections:
- name: ansible.windows
  version: '>=1.7.0'

- name: chocolatey.chocolatey

- name: community.general
  version: '>=3.0.0'

- name: community.windows
